language: node_js

node_js:
  - "8.12.0"

sudo: true

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE db_jl_express_js_test;" -U postgres
  - node_modules/.bin/sequelize db:migrate
